# Introduction to NumPy

In [1]:
import numpy
numpy.__version__

'1.23.5'

In [2]:
import numpy as np

In [3]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\onkar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\onkar\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets a

## Fixed Type Arrays in Python

In [4]:
import array
L = list(range(10))
A = array.array('i', L) # 'i' indicates that contents are integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating Arrays from Python Lists

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([1,2,3.14,4,5]) # NumPy will upcast if types do not match

array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [7]:
np.array([1,2,3.14,4,5],dtype='float32') # Data type can be explicitly set using keyword 'dtype'

array([1.  , 2.  , 3.14, 4.  , 5.  ], dtype=float32)

In [8]:
np.array([range(i,i+3) for i in range(2,7,2)]) # nested lists are converted to multidimensional arrays

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch