# Introduction to NumPy

In [1]:
import numpy
numpy.__version__

'1.24.0'

In [2]:
import numpy as np

In [3]:
np?

## Fixed Type Arrays in Python

In [4]:
import array
L = list(range(10))
A = array.array('i', L)  # 'i' indicates that contents are integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating Arrays from Python Lists

In [5]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([1, 2, 3.14, 4, 5])  # NumPy will upcast if types do not match

array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [7]:
# Data type can be explicitly set using keyword 'dtype'
np.array([1, 2, 3.14, 4, 5], dtype='float32')

array([1.  , 2.  , 3.14, 4.  , 5.  ], dtype=float32)

In [8]:
# nested lists are converted to multidimensional arrays
np.array([range(i, i+3) for i in range(2, 7, 2)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [9]:
np.zeros(10, dtype="int")  # length 10 int array with zeroes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3, 5), dtype="float")  # 3*5 floating-point array with ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3, 5), 3.14)  # 3*5 floating-point array with 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
np.arange(0, 20, 2)  # starting at 0, ending at 20, sstepping size 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0, 1, 5)  # 5 values evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# 3*3 array (uniformly distributed) with random values between 0 and 1
np.random.random((3, 3))

array([[0.61673813, 0.23526959, 0.84862605],
       [0.58103813, 0.82530799, 0.79449075],
       [0.42521592, 0.9867539 , 0.91348948]])

In [15]:
# 3*3 array (normally distributed) with random values between 0 and 1
np.random.normal((3, 3))

array([2.9048056 , 2.90236176])

In [16]:
# 3*3 array with random int in interval [0,10)
np.random.randint(0, 10, (3, 3))

array([[2, 2, 6],
       [9, 9, 6],
       [5, 0, 6]])

In [17]:
np.eye(3)  # 3*3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# uninitialized array of 3 int with value from previous allocation in that memory location
np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types

| Data Type | Description |
| -: | :--- |
| bool_ | Boolean (True or False) stored as a byte |
| int_ | Default integer type (same as C long; normally either int64 or int32) |
| intc | Identical to C int (normally int32 or int64) |
| intp | Integer used for indexing (same as C ssize_t; normally either int32 or int64) |
| int8 | Integer (–127 to 128) |
| int16 | Integer (–32768 to 32767) |
| int32 | Integer (–2147483648 to 2147483647) |
| int64 | Integer (–9223372036854775808 to 9223372036854775807) |
| uint8 | Unsigned integer (0 to 255) |
| uint16 | Unsigned integer (0 to 65535) |
| uint32 | Unsigned integer (0 to 4294967295) |
| uint64 | Unsigned integer (0 to 18446744073709551615) |
| float_ | Shorthand for float64 |
| float16 | Half-precision foat: sign bit, 5 bits exponent, 10 bits mantissa |
| float32 | Single-precision foat: sign bit, 8 bits exponent, 23 bits mantissa |
| float64 | Double-precision foat: sign bit, 11 bits exponent, 52 bits mantissa |
| complex_ | Shorthand for complex128 |
| complex64 | Complex number, represented by two 32-bit foats |
| complex128 | Complex number, represented by two 64-bit foats |

In [19]:
np.zeros(10, dtype="int16")  # length 10 int16 array with zeroes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [20]:
np.zeros(10, dtype=np.int16)  # np.int16 is associated NumPy object

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)