# The Basics of NumPy Arrays

In [1]:
import numpy as np
np.__version__

'1.24.0'

## NumPy Array Attributes

In [2]:
np.random.seed(0)  # seed for reproducibility

In [3]:
x1 = np.random.randint(10, size=6)  # one-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # three-dimensional array

In [4]:
print("x3 ndim :", x3.ndim)
print("x3 shape :", x3.shape)
print("x3 size :", x3.size)

x3 ndim : 3
x3 shape : (3, 4, 5)
x3 size : 60


In [5]:
print("dtype :", x3.dtype)

dtype : int32


In [6]:
print("itemsize :", x3.itemsize, "bytes")
print("nbytes :", x3.nbytes, "bytes")

itemsize : 4 bytes
nbytes : 240 bytes


## Array Indexing: Accessing Single Elements

In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0]

5

In [9]:
x1[4]

7

In [10]:
x1[-1]

9

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[0, 0]

3

In [13]:
x2[2, 0]

1

In [14]:
x2[2, -1]

7

In [15]:
x2[0, 0] = 2
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [16]:
x1[0] = 3.14159  # this will be truncated
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

### One-dimensional Subarrays

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[:5]  # first 5 elements

array([0, 1, 2, 3, 4])

In [19]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [20]:
x[4:7]  # middle subarray

array([4, 5, 6])

In [21]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [22]:
x[1::2]  # every other element starting at index 1

array([1, 3, 5, 7, 9])

In [23]:
x[::-1]  # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multidimensional Subarrays

In [25]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [26]:
x2[:2, :3]  # two rows and three columns

array([[2, 5, 2],
       [7, 6, 8]])

In [27]:
x2[:3, ::2]  # three rows and every other column

array([[2, 2],
       [7, 8],
       [1, 7]])

In [28]:
x2[::1, ::-1]  # subarrays reversed

array([[4, 2, 5, 2],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [29]:
x2[::1, ::-1]  # arrays and subarray reversed together

array([[4, 2, 5, 2],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

### Accessing Array Rows and Columns

In [30]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
x2[:, 0]  # first column of x2

array([2, 7, 1])

In [32]:
x2[0, :]  # first row of x2

array([2, 5, 2, 4])

In [33]:
x2[0]  # equivalent to x2[0,:]

array([2, 5, 2, 4])

 ### Subarrays as No-Copy Views

In [34]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
# array slicing returns views rather than copies of the data
x2_sub = x2[:2, :2]
x2_sub

array([[2, 5],
       [7, 6]])

In [36]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [37]:
x2  # original array is also changed

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Creating Copies of Arrays

In [38]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
# copy() method is used to explicitly copy data within an array
x2_sub = x2[:2, :2].copy()
x2_sub

array([[99,  5],
       [ 7,  6]])

In [40]:
x2_sub[0, 0] = 42
x2_sub

array([[42,  5],
       [ 7,  6]])

In [41]:
x2  # original array is not changed

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Reshaping Arrays

In [42]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
grid = grid.reshape((3, 3))  # reshape() is used for reshaping arrays
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [45]:
x.reshape((1, 3))  # row vector via reshape

array([[1, 2, 3]])

In [46]:
x.reshape((3, 1))  # column vector via reshape

array([[1],
       [2],
       [3]])

In [47]:
x[np.newaxis, :]  # row vector via newaxis

array([[1, 2, 3]])

In [48]:
x[:, np.newaxis]  # column vector via newaxis

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

### Concatenation of Arrays

In [49]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

# np.concatenate() takes a tuple or list of arrays as its first argument
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [50]:
z = np.array([99, 99, 99])
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [51]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate([grid, grid])  # concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [54]:
np.vstack([x, grid])  # vertically stack the arrays (along the first axis)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
w = np.array([[99], [98]])

np.hstack([grid, w])  # horizontally stack the arrays (along the second axis)

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 98]])

In [56]:
np.dstack([grid, grid])  # diagonally stack the arrays (along the third axis)

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

### Splitting of Arrays

In [57]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

x1, x2, x3 = np.split(x, [3, 5])  # split(x,[3,5]) splits x at position 3 and 5
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [58]:
grid = np.arange(16).reshape([4, 4])
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
# vsplit(grid,[2]) splits grid vertically at position 2
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [60]:
# hsplit(grid,[2]) splits grid horizontally at position 2
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [61]:
y = np.arange(16).reshape([2, 2, 4])
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [62]:
# dsplit(y,[2]) splits y along third axis at position 2
d1, d2 = np.dsplit(y, [2])
print(d1)
print(d2)

[[[ 0  1]
  [ 4  5]]

 [[ 8  9]
  [12 13]]]
[[[ 2  3]
  [ 6  7]]

 [[10 11]
  [14 15]]]
