# Computation on NumPy Arrays: Universal Functions

In [1]:
import numpy as np
np.__version__

'1.24.0'

## The Slowness of Loops

In [2]:
np.random.seed(0)

In [3]:
def compute_reciprocals(values):
    output = np.empty(len(values))

    for i in range(len(values)):
        output[i] = 1.0 / values[i]

    return output

In [4]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

383 ms ± 4.52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Introducing UFuncs

In [6]:
print(compute_reciprocals(values))
print(1.0 / values)  # vectorized operation

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [8]:
%timeit (1.0 / big_array)

5.68 ms ± 934 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
np.arange(5) / np.arange(1, 6)  # division of corresponding entries

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [10]:
# UFuncs can act on multidimensional arrays as well
x = np.arange(9).reshape((3, 3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

## Exploring NumPy's UFuncs

### Array Arithmetic

In [11]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [12]:
print("-x = ", -x)
print("x ** 2 = ", x**2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [13]:
-((0.5 * x + 1) ** 2)

array([-1.  , -2.25, -4.  , -6.25])

In [14]:
np.add(x, 2)

array([2, 3, 4, 5])

### Absolute Value

### Trigonometric Functions

 ### Exponents and Logarithms

### Specialized UFuncs

## Advanced UFunc Features

### Specifying Output

### Aggregates

### Outer Products